"""Tests for scripts/release.py: release notes written in PRs, versions assigned after merge.

Every PR used to bump `version` in Cargo.toml and write
`src/release_notes/<version>.md`. Every open PR then edited the same line, so
each merge put every other open PR in conflict, and a PR whose number main
reached had to move its version and rename its notes. Now a PR writes a
fragment, `src/release_notes/unreleased/<name>.md`, whose name no other PR
shares, and never touches the version. After a merge, `release.py cut` folds
the fragments into the next version's notes and bumps the version, once, on
main.

`check` is the PR gate and `cut` is what the version-bump workflow runs. Both
are pinned here in both directions: what they must accept as much as what they
must refuse.
"""

from __future__ import annotations

import io
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from contextlib import redirect_stdout
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts"))

import release  # noqa: E402

CI = ROOT / ".github" / "workflows" / "ci.yml"
VERSION_BUMP = ROOT / ".github" / "workflows" / "version-bump.yml"
GATE_STEP = "Shipped changes add release notes and leave the version alone"
BUMP_STEP = "Fold the notes, bump the version and push"
# What the steps run, copied into the throwaway repos they run in.
SCRIPTS = ["release.py", "next_version.py", "ships_nothing.py", "check_doc_ownership.py"]

CARGO_TOML = '''[package]
name = "croft-software"
version = "0.2.11"
edition = "2024"

[dependencies]
serde = { version = "0.2.11" }

[dependencies.toml]
version = "0.2.11"
'''

# The lockfile's own format line, a dependency that happens to share the
# version, and croft's stanza with a field between `name` and `version`, so a
# rewrite that matched the first `version` line, or assumed it follows `name`,
# would show.
CARGO_LOCK = '''# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "anstyle"
version = "0.2.11"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "croft-software"
source = "path+file:///work"
version = "0.2.11"
dependencies = [
 "anstyle",
]
'''

SHIPPED = "pub fn width(cols: u16) -> u16 {\n    cols / 2\n}\n"

README = "Unreleased notes: one file per change. See CONTRIBUTING.md.\n"


def run(cwd, *args):
    return subprocess.run(args, cwd=cwd, check=True, capture_output=True, text=True).stdout


class Repo:
    """A throwaway croft-shaped repo on `main`, released at 0.2.11."""

    def __init__(self, tmp: Path):
        self.path = tmp
        run(tmp, "git", "init", "-q", "-b", "main")
        run(tmp, "git", "config", "user.email", "t@example.com")
        run(tmp, "git", "config", "user.name", "t")
        self.write("Cargo.toml", CARGO_TOML)
        self.write("Cargo.lock", CARGO_LOCK)
        self.write("src/lib.rs", SHIPPED)
        self.write("src/release_notes/0.2.11.md", "fix: The last release.\n")
        self.write("src/release_notes/unreleased/README.md", README)
        self.write("docs/GUIDE.md", "A guide.\n")
        self.commit()

    def write(self, name: str, text: str):
        path = self.path / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)

    def remove(self, name: str):
        (self.path / name).unlink()

    def read(self, name: str) -> str:
        return (self.path / name).read_text()

    def exists(self, name: str) -> bool:
        return (self.path / name).exists()

    def commit(self):
        run(self.path, "git", "add", "-A")
        run(self.path, "git", "commit", "-q", "-m", "c")

    def branch(self):
        run(self.path, "git", "checkout", "-q", "-b", "work")

    def check(self):
        """The gate's verdict on `work` against `main`: (errors, printed)."""
        out = io.StringIO()
        with redirect_stdout(out):
            errors = release.check("main", "HEAD", cwd=self.path)
        return errors, out.getvalue()

    def cut(self, kind="patch"):
        return release.cut(self.path, kind)


def joined(errors):
    return "\n".join(errors)


class Check(unittest.TestCase):
    """The PR gate: a shipped change carries a fragment and leaves the version alone."""

    def test_a_shipped_change_with_a_fragment_passes(self):
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            repo.branch()
            repo.write("src/lib.rs", SHIPPED.replace("/ 2", "/ 3"))
            repo.write("src/release_notes/unreleased/860-width.md", "fix: Width halves no more.\n")
            repo.commit()
            errors, _ = repo.check()
            self.assertEqual(errors, [])

    def test_a_shipped_change_without_a_fragment_fails(self):
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            repo.branch()
            repo.write("src/lib.rs", SHIPPED.replace("/ 2", "/ 3"))
            repo.commit()
            errors, _ = repo.check()
            self.assertIn("src/release_notes/unreleased/", joined(errors))

    def test_bumping_the_version_in_a_pr_fails(self):
        """The line every open PR used to fight over. The workflow assigns
        the version after merge, so a PR that sets one is refused even with a
        fragment."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            repo.branch()
            repo.write("src/lib.rs", SHIPPED.replace("/ 2", "/ 3"))
            repo.write("Cargo.toml", CARGO_TOML.replace('version = "0.2.11"\nedition', 'version = "0.2.12"\nedition'))
            repo.write("src/release_notes/unreleased/860-width.md", "fix: Width.\n")
            repo.commit()
            errors, _ = repo.check()
            self.assertIn("0.2.11", joined(errors))
            self.assertIn("0.2.12", joined(errors))

    def test_writing_a_versions_notes_in_a_pr_fails(self):
        """A version's notes are written by `cut`, after merge. A PR that
        writes one, the old way, is pointed at a fragment instead."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            repo.branch()
            repo.write("src/lib.rs", SHIPPED.replace("/ 2", "/ 3"))
            repo.write("src/release_notes/0.2.12.md", "fix: Width.\n")
            repo.commit()
            errors, _ = repo.check()
            self.assertIn("src/release_notes/0.2.12.md", joined(errors))

    def test_editing_a_released_versions_notes_fails(self):
        """A released version's notes describe a binary already out there."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            repo.branch()
            repo.write("src/release_notes/0.2.11.md", "fix: Rewritten history.\n")
            repo.commit()
            errors, _ = repo.check()
            self.assertIn("src/release_notes/0.2.11.md", joined(errors))

    def test_a_fragment_with_no_highlight_fails(self):
        """The same filter the build applies: a heading alone is not a
        highlight, and an empty card would get past a non-blank check."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            repo.branch()
            repo.write("src/lib.rs", SHIPPED.replace("/ 2", "/ 3"))
            repo.write("src/release_notes/unreleased/860-width.md", "# Width\n\n")
            repo.commit()
            errors, _ = repo.check()
            self.assertIn("860-width.md", joined(errors))

    def test_editing_the_unreleased_readme_is_not_a_fragment(self):
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            repo.branch()
            repo.write("src/lib.rs", SHIPPED.replace("/ 2", "/ 3"))
            repo.write("src/release_notes/unreleased/README.md", README + "fix: Not a note.\n")
            repo.commit()
            errors, _ = repo.check()
            self.assertIn("src/release_notes/unreleased/", joined(errors))

    def test_a_hidden_file_is_not_a_fragment(self):
        """The build and the cut skip dot-files (an editor's `.#name.md` lock
        file), so the gate must not count one as the PR's notes."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            repo.branch()
            repo.write("src/lib.rs", SHIPPED.replace("/ 2", "/ 3"))
            repo.write("src/release_notes/unreleased/.860-width.md", "fix: Width.\n")
            repo.commit()
            errors, _ = repo.check()
            self.assertIn("adds no release notes", joined(errors))

    def test_a_docs_only_change_needs_no_fragment(self):
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            repo.branch()
            repo.write("docs/GUIDE.md", "A better guide.\n")
            repo.commit()
            errors, out = repo.check()
            self.assertEqual(errors, [])
            self.assertIn("No shipped files changed", out)

    def test_a_test_only_change_inside_a_shipped_file_needs_no_fragment(self):
        """The exemption ships_nothing.py gives the old gate (#461) carries
        over unchanged."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            tested = SHIPPED + "\n#[cfg(test)]\nmod tests {\n    #[test]\n    fn t() {}\n}\n"
            repo.write("src/lib.rs", tested)
            repo.commit()
            repo.branch()
            repo.write("src/lib.rs", tested.replace("fn t() {}", "fn t() { assert!(true) }"))
            repo.commit()
            errors, _ = repo.check()
            self.assertEqual(errors, [])

    def test_editing_a_pending_fragment_alone_needs_no_new_one(self):
        """A typo fix in a note that has not shipped yet changes no code, so
        it does not owe a note of its own."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            repo.write("src/release_notes/unreleased/860-width.md", "fix: Widht.\n")
            repo.commit()
            repo.branch()
            repo.write("src/release_notes/unreleased/860-width.md", "fix: Width.\n")
            repo.commit()
            errors, _ = repo.check()
            self.assertEqual(errors, [])

    def test_deleting_a_pending_fragment_fails(self):
        """A note on main waits for the next release; a PR that deletes it,
        even one that ships nothing, would have that release leave it out
        without a word (Greptile, #1159)."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            repo.write("src/release_notes/unreleased/860-width.md", "fix: Width.\n")
            repo.commit()
            repo.branch()
            repo.remove("src/release_notes/unreleased/860-width.md")
            repo.write("docs/GUIDE.md", "A better guide.\n")
            repo.commit()
            errors, _ = repo.check()
            self.assertIn("deletes src/release_notes/unreleased/860-width.md", joined(errors))

    def test_renaming_a_pending_fragment_passes(self):
        """The guard: a note moved to another name, its text unchanged, is
        still released."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            repo.write("src/release_notes/unreleased/width.md", "fix: Width.\n")
            repo.commit()
            repo.branch()
            repo.remove("src/release_notes/unreleased/width.md")
            repo.write("src/release_notes/unreleased/860-width.md", "fix: Width.\n")
            repo.commit()
            errors, _ = repo.check()
            self.assertEqual(errors, [])

    def test_editing_a_pending_fragment_to_say_nothing_fails(self):
        """An edit that leaves a pending note without a highlight would stop
        the cut on main after merge, so the PR fails instead."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            repo.write("src/release_notes/unreleased/860-width.md", "fix: Width.\n")
            repo.commit()
            repo.branch()
            repo.write("src/release_notes/unreleased/860-width.md", "# Width\n")
            repo.commit()
            errors, _ = repo.check()
            self.assertIn("860-width.md carries no highlights", joined(errors))

    def test_a_git_failure_is_one_error_line_not_a_traceback(self):
        """A base the clone does not have (a shallow checkout, a mistyped
        ref) made git fail inside the gate, and CI showed a Python
        traceback. It is one `::error::` line naming the git command, and
        a non-zero exit (Copilot, #1159)."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            out = subprocess.run(
                [sys.executable, str(ROOT / "scripts" / "release.py"), "check", "no-such-ref", "HEAD"],
                cwd=repo.path,
                capture_output=True,
                text=True,
                check=False,
            )
            self.assertEqual(out.returncode, 1, out.stdout + out.stderr)
            self.assertNotIn("Traceback", out.stdout + out.stderr)
            self.assertIn("::error::git diff", out.stdout + out.stderr)

    def test_a_stacked_prs_fragments_both_count(self):
        """GitHub tests a PR stacked on another as both merged into main, so
        the gate sees two fragments. The old gate allowed one notes file per
        PR and failed every stacked PR this way (#883)."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            repo.branch()
            repo.write("src/lib.rs", SHIPPED.replace("/ 2", "/ 3"))
            repo.write("src/release_notes/unreleased/852-palette.md", "feature: Palette.\n")
            repo.write("src/release_notes/unreleased/860-search.md", "feature: Search keys.\n")
            repo.commit()
            errors, _ = repo.check()
            self.assertEqual(errors, [])


class Cut(unittest.TestCase):
    """After a merge: fold the fragments into the next version's notes, bump once."""

    def test_fragments_fold_into_the_next_versions_notes_in_name_order(self):
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            repo.write("src/release_notes/unreleased/862-hot-exit.md", "feature: Hot exit.\n")
            repo.write("src/release_notes/unreleased/847-plot.md", "fix: Plot lines join.\nfix: Labels.\n")
            repo.commit()
            self.assertEqual(repo.cut(), "0.2.12")
            self.assertEqual(
                repo.read("src/release_notes/0.2.12.md"),
                "fix: Plot lines join.\nfix: Labels.\nfeature: Hot exit.\n",
            )
            self.assertFalse(repo.exists("src/release_notes/unreleased/847-plot.md"))
            self.assertFalse(repo.exists("src/release_notes/unreleased/862-hot-exit.md"))
            self.assertEqual(repo.read("src/release_notes/unreleased/README.md"), README)

    def test_the_version_moves_in_cargo_toml_and_croft_s_lock_entry_only(self):
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            repo.write("src/release_notes/unreleased/847-plot.md", "fix: Plot.\n")
            repo.commit()
            repo.cut()
            self.assertEqual(
                repo.read("Cargo.toml"),
                CARGO_TOML.replace('version = "0.2.11"\nedition', 'version = "0.2.12"\nedition'),
            )
            self.assertEqual(
                repo.read("Cargo.lock"),
                CARGO_LOCK.replace(
                    'source = "path+file:///work"\nversion = "0.2.11"',
                    'source = "path+file:///work"\nversion = "0.2.12"',
                ),
            )

    def test_the_bump_counts_like_an_odometer(self):
        """The cap next_version.py enforces carries over: 0.2.999 is followed
        by 0.3.0, and a minor or major bump resets what is below it."""
        for current, kind, expected in [
            ("0.2.999", "patch", "0.3.0"),
            ("0.2.11", "minor", "0.3.0"),
            ("0.2.11", "major", "1.0.0"),
        ]:
            with tempfile.TemporaryDirectory() as tmp:
                repo = Repo(Path(tmp))
                repo.write("Cargo.toml", CARGO_TOML.replace("0.2.11", current))
                repo.write("Cargo.lock", CARGO_LOCK.replace("0.2.11", current))
                repo.write("src/release_notes/unreleased/x.md", "fix: X.\n")
                repo.commit()
                self.assertEqual(repo.cut(kind), expected, (current, kind))
                self.assertTrue(repo.exists(f"src/release_notes/{expected}.md"))

    def test_hidden_files_are_not_folded(self):
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            repo.write("src/release_notes/unreleased/.#847-plot.md", "fix: A lock file.\n")
            repo.write("src/release_notes/unreleased/848-edit.md", "fix: Edit.\n")
            repo.commit()
            self.assertEqual(repo.cut(), "0.2.12")
            self.assertEqual(repo.read("src/release_notes/0.2.12.md"), "fix: Edit.\n")

    def test_nothing_pending_releases_nothing(self):
        """A merge that shipped nothing (docs, CI, tests) leaves no fragment,
        and must not cut an empty release."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            self.assertIsNone(repo.cut())
            self.assertEqual(repo.read("Cargo.toml"), CARGO_TOML)
            self.assertEqual(repo.read("Cargo.lock"), CARGO_LOCK)
            self.assertFalse(repo.exists("src/release_notes/0.2.12.md"))

    def test_a_fragment_with_no_highlight_stops_the_cut_and_changes_nothing(self):
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            repo.write("src/release_notes/unreleased/847-plot.md", "fix: Plot.\n")
            repo.write("src/release_notes/unreleased/848-edit.md", "# Edit\n")
            repo.commit()
            with self.assertRaises(release.ReleaseError) as caught:
                repo.cut()
            self.assertIn("848-edit.md", str(caught.exception))
            self.assertEqual(repo.read("Cargo.toml"), CARGO_TOML)
            self.assertTrue(repo.exists("src/release_notes/unreleased/847-plot.md"))
            self.assertFalse(repo.exists("src/release_notes/0.2.12.md"))

    def test_an_existing_notes_file_for_the_next_version_is_never_overwritten(self):
        """A file already at the next version's path describes something; the
        cut stops rather than replace it."""
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            repo.write("src/release_notes/0.2.12.md", "fix: Already here.\n")
            repo.write("src/release_notes/unreleased/847-plot.md", "fix: Plot.\n")
            repo.commit()
            with self.assertRaises(release.ReleaseError) as caught:
                repo.cut()
            self.assertIn("0.2.12.md", str(caught.exception))
            self.assertEqual(repo.read("src/release_notes/0.2.12.md"), "fix: Already here.\n")
            self.assertEqual(repo.read("Cargo.toml"), CARGO_TOML)

    def test_a_lockfile_without_exactly_one_croft_entry_stops_the_cut(self):
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            repo.write("Cargo.lock", CARGO_LOCK.replace('name = "croft-software"', 'name = "other"'))
            repo.write("src/release_notes/unreleased/847-plot.md", "fix: Plot.\n")
            repo.commit()
            with self.assertRaises(release.ReleaseError):
                repo.cut()
            self.assertEqual(repo.read("Cargo.toml"), CARGO_TOML)
            self.assertTrue(repo.exists("src/release_notes/unreleased/847-plot.md"))


def step_script(workflow: Path, name: str) -> str:
    """A step's `run:` block, exactly as the workflow file has it."""
    lines = workflow.read_text().splitlines()
    start = next(i for i, line in enumerate(lines) if line.strip() == f"- name: {name}")
    run_at = next(i for i in range(start, len(lines)) if lines[i].strip() == "run: |")
    run_indent = len(lines[run_at]) - len(lines[run_at].lstrip())
    body = []
    for line in lines[run_at + 1 :]:
        if line.strip() and len(line) - len(line.lstrip()) <= run_indent:
            break
        body.append(line)
    body_indent = min(len(l) - len(l.lstrip()) for l in body if l.strip())
    return "\n".join(l[body_indent:] for l in body)


def with_scripts(repo: Repo):
    for name in SCRIPTS:
        repo.write(f"scripts/{name}", (ROOT / "scripts" / name).read_text())


class VersionBumpShape(unittest.TestCase):
    """What the version-bump workflow's YAML says about when it runs, read
    from the file: GitHub, not a step, acts on these keys."""

    def block(self, key: str) -> list[str]:
        """The lines of the top-level `key:` block."""
        lines = VERSION_BUMP.read_text().splitlines()
        start = lines.index(f"{key}:")
        body = []
        for line in lines[start + 1 :]:
            if line and not line.startswith((" ", "#")):
                break
            body.append(line.strip())
        return body

    def test_queued_runs_wait_their_turn(self):
        """A concurrency group keeps one pending run by default, and a newer
        run replaces it: a minor or major release asked for by hand, queued
        behind a running release, was replaced by the next merge's patch run
        and its notes went out as a patch (Greptile, #1159). `queue: max`
        keeps every queued run."""
        concurrency = self.block("concurrency")
        self.assertIn("queue: max", concurrency)
        self.assertIn("cancel-in-progress: false", concurrency)

    def test_no_commit_message_keeps_a_push_from_releasing(self):
        """The job skipped any push whose head commit message began
        "chore: release ", which a merged PR's title can do, leaving its
        notes pending (Greptile, #1159). The job's own release commit needs
        no skip: its run finds nothing pending and pushes nothing (see
        `test_the_version_bump_step_with_nothing_pending_pushes_nothing`)."""
        self.assertNotIn("head_commit", VERSION_BUMP.read_text())


@unittest.skipUnless(shutil.which("bash") and shutil.which("git"), "needs bash and git")
class Workflows(unittest.TestCase):
    """A rule nothing enforces is a suggestion: the steps themselves, taken
    from the workflow files, run against throwaway repos."""

    def gate(self, repo: Repo) -> subprocess.CompletedProcess[str]:
        run(repo.path, "git", "update-ref", "refs/remotes/origin/main", "main")
        return subprocess.run(
            ["bash", "-c", step_script(CI, GATE_STEP)],
            cwd=repo.path,
            env={**os.environ, "GITHUB_BASE_REF": "main"},
            capture_output=True,
            text=True,
            check=False,
        )

    def test_the_ci_step_refuses_a_version_bump_and_wants_a_fragment(self):
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            with_scripts(repo)
            repo.commit()
            repo.branch()
            repo.write("src/lib.rs", SHIPPED.replace("/ 2", "/ 3"))
            repo.write("Cargo.toml", CARGO_TOML.replace('version = "0.2.11"\nedition', 'version = "0.2.12"\nedition'))
            repo.write("src/release_notes/0.2.12.md", "fix: Width.\n")
            repo.commit()
            out = self.gate(repo)
            self.assertNotEqual(out.returncode, 0, out.stdout)
            self.assertIn("changes the version from 0.2.11 to 0.2.12", out.stdout)
            self.assertIn("src/release_notes/0.2.12.md", out.stdout)
            self.assertIn("adds no release notes", out.stdout)

    def test_the_ci_step_passes_a_fragment(self):
        with tempfile.TemporaryDirectory() as tmp:
            repo = Repo(Path(tmp))
            with_scripts(repo)
            repo.commit()
            repo.branch()
            repo.write("src/lib.rs", SHIPPED.replace("/ 2", "/ 3"))
            repo.write("src/release_notes/unreleased/860-width.md", "fix: Width.\n")
            repo.commit()
            out = self.gate(repo)
            self.assertEqual(out.returncode, 0, out.stdout + out.stderr)

    def bump(self, tmp: Path, pending: dict[str, str], racing: dict[str, str] | None = None):
        """Run the version-bump step in a clone of a bare `origin` whose main
        holds `pending` fragments. Returns the result and origin's path.

        With `racing`, another merge adding those fragments lands on origin's
        main after the step has cut and committed: origin refuses the step's
        first push, as GitHub refuses a push that is not a fast-forward."""
        (tmp / "seed").mkdir()
        seed = Repo(tmp / "seed")
        with_scripts(seed)
        for name, text in pending.items():
            seed.write(f"src/release_notes/unreleased/{name}", text)
        seed.commit()
        origin = tmp / "origin.git"
        run(tmp, "git", "clone", "-q", "--bare", str(seed.path), str(origin))
        if racing:
            for name, text in racing.items():
                seed.write(f"src/release_notes/unreleased/{name}", text)
            seed.write("src/lib.rs", SHIPPED.replace("/ 2", "/ 4"))
            run(seed.path, "git", "add", "-A")
            run(seed.path, "git", "commit", "-q", "-m", "the racing merge")
            run(seed.path, "git", "push", "-q", str(origin), "main:refs/heads/racing")
            # The hook runs in git's push quarantine, where ref updates are
            # refused; the racing commit is already in origin's own store.
            hook = origin / "hooks" / "pre-receive"
            hook.write_text(
                "#!/bin/sh\n"
                "[ -e raced ] && exit 0\n"
                "touch raced\n"
                "env -u GIT_QUARANTINE_PATH -u GIT_OBJECT_DIRECTORY -u GIT_ALTERNATE_OBJECT_DIRECTORIES \\\n"
                "  git update-ref refs/heads/main refs/heads/racing\n"
                "echo 'main moved on' >&2\n"
                "exit 1\n"
            )
            hook.chmod(0o755)
        work = tmp / "work"
        run(tmp, "git", "clone", "-q", str(origin), str(work))
        summary = tmp / "summary.md"
        out = subprocess.run(
            ["bash", "-c", step_script(VERSION_BUMP, BUMP_STEP)],
            cwd=work,
            env={**os.environ, "BUMP": "patch", "GITHUB_STEP_SUMMARY": str(summary)},
            capture_output=True,
            text=True,
            check=False,
        )
        return out, origin

    def test_the_version_bump_step_releases_and_pushes_one_commit(self):
        with tempfile.TemporaryDirectory() as tmp:
            out, origin = self.bump(Path(tmp), {"847-plot.md": "fix: Plot.\n"})
            self.assertEqual(out.returncode, 0, out.stdout + out.stderr)
            log = run(origin, "git", "log", "--format=%an|%s", "-2", "main").splitlines()
            self.assertEqual(log[0], "github-actions[bot]|chore: release 0.2.12")
            self.assertEqual(log[1], "t|c", "one commit on top of what was there")
            self.assertEqual(run(origin, "git", "show", "main:src/release_notes/0.2.12.md"), "fix: Plot.\n")
            self.assertIn('version = "0.2.12"', run(origin, "git", "show", "main:Cargo.toml"))
            files = run(origin, "git", "ls-tree", "-r", "--name-only", "main", "src/release_notes/unreleased")
            self.assertEqual(files.split(), ["src/release_notes/unreleased/README.md"])

    def test_a_merge_that_lands_before_the_push_is_released_with_it(self):
        """Two merges close together: the second lands on main while the run
        for the first is between its cut and its push. The push is refused,
        and the step cuts again on the new main, so one release holds both
        merges' notes. A run that pushed once and gave up would fail here and
        leave the first merge's notes for whichever run came next."""
        with tempfile.TemporaryDirectory() as tmp:
            out, origin = self.bump(
                Path(tmp),
                {"847-plot.md": "fix: Plot.\n"},
                racing={"862-hot-exit.md": "feature: Hot exit.\n"},
            )
            self.assertEqual(out.returncode, 0, out.stdout + out.stderr)
            self.assertIn("main moved while releasing 0.2.12", out.stdout)
            log = run(origin, "git", "log", "--format=%an|%s", "-2", "main").splitlines()
            self.assertEqual(log, ["github-actions[bot]|chore: release 0.2.12", "t|the racing merge"])
            self.assertEqual(
                run(origin, "git", "show", "main:src/release_notes/0.2.12.md"),
                "fix: Plot.\nfeature: Hot exit.\n",
            )
            files = run(origin, "git", "ls-tree", "-r", "--name-only", "main", "src/release_notes/unreleased")
            self.assertEqual(files.split(), ["src/release_notes/unreleased/README.md"])

    def test_the_version_bump_step_with_nothing_pending_pushes_nothing(self):
        with tempfile.TemporaryDirectory() as tmp:
            out, origin = self.bump(Path(tmp), {})
            self.assertEqual(out.returncode, 0, out.stdout + out.stderr)
            self.assertIn("nothing to release", out.stdout)
            self.assertEqual(run(origin, "git", "log", "--format=%s", "-1", "main").strip(), "c")

    def test_the_version_bump_step_stops_on_a_fragment_that_says_nothing(self):
        with tempfile.TemporaryDirectory() as tmp:
            out, origin = self.bump(Path(tmp), {"848-edit.md": "# Edit\n"})
            self.assertNotEqual(out.returncode, 0)
            self.assertIn("848-edit.md", out.stderr)
            self.assertEqual(run(origin, "git", "log", "--format=%s", "-1", "main").strip(), "c")


if __name__ == "__main__":
    unittest.main()
